# Azure AI Foundry account and model deployments, Sweden Central (ADR-0002: model data
# stays in the EU; tier 3 in docs/method/risk-tiering.md narrows Restricted-data routing
# to own-tenancy or self-hosted models — this account is the own-tenancy half of that
# rule). LiteLLM (ADR-0003) reaches it as just another provider behind the gateway.

resource "azurerm_cognitive_account" "foundry" {
  name                = local.names.ai_services
  resource_group_name = azurerm_resource_group.lab.name
  location            = azurerm_resource_group.lab.location
  kind                = "AIServices"
  sku_name            = "S0"

  # Must match the account name: verified with `az cognitiveservices account list-kinds`
  # and the AIServices kind's subdomain requirement.
  custom_subdomain_name = local.names.ai_services

  # LiteLLM authenticates with the account key for now (stored in Key Vault below).
  # Entra-only auth (local_auth_enabled = false, gateway uses a managed identity
  # instead of the key) is a later step, once the gateway workload exists to test it
  # against — flipping this without that in place would just break the route.
  # checkov:skip=CKV_AZURE_236: deliberate for now; see the comment above. Revisit
  # when the gateway can authenticate with a managed identity instead of the key.
  local_auth_enabled = true

  # checkov:skip=CKV_AZURE_134: lab tier; the production placement uses a private
  # endpoint (ADR-0002). Public access is required for now for the same reason as
  # the Key Vault above — the gateway does not yet run inside the Azure VNet.
  public_network_access_enabled = true

  # checkov:skip=CKV2_AZURE_22: customer-managed keys are production hardening
  # (ADR-0002's private-endpoint placement), not a lab-tier control; Microsoft-managed
  # keys are the provider default and adequate for the lab's non-production data.
  identity {
    type = "SystemAssigned"
  }

  tags = var.tags
}

# gpt-5.4-mini: `az cognitiveservices model list -l swedencentral` shows this model
# format OpenAI, version 2026-03-17, does not offer the regional "Standard" SKU in
# Sweden Central — only GlobalStandard, DataZoneStandard and the provisioned/batch
# SKUs. GlobalStandard is excluded by policy (data leaves the EU data zone), so this
# uses DataZoneStandard: EU data zone, not pinned to Sweden Central specifically, but
# still inside the EU residency boundary ADR-0002 requires.
resource "azurerm_cognitive_deployment" "gpt_5_4_mini" {
  name                 = "gpt-5.4-mini"
  cognitive_account_id = azurerm_cognitive_account.foundry.id

  model {
    format  = "OpenAI"
    name    = "gpt-5.4-mini"
    version = "2026-03-17"
  }

  sku {
    name     = "DataZoneStandard"
    capacity = 10
  }

  # Pins the deployment to this model version; an upgrade is a deliberate change, not
  # something Azure does on our behalf. Stated control in ADR-0003 (version pinning).
  version_upgrade_option = "NoAutoUpgrade"
}

# gpt-4.1-mini: the same `az cognitiveservices model list` output shows the regional
# "Standard" SKU is offered for this model/version in Sweden Central, so data stays in
# region per ADR-0002 rather than only in the EU data zone.
resource "azurerm_cognitive_deployment" "gpt_4_1_mini" {
  name                 = "gpt-4.1-mini"
  cognitive_account_id = azurerm_cognitive_account.foundry.id

  model {
    format  = "OpenAI"
    name    = "gpt-4.1-mini"
    version = "2025-04-14"
  }

  sku {
    name     = "Standard"
    capacity = 10
  }

  version_upgrade_option = "NoAutoUpgrade"
}

# The key and endpoint transit Terraform state, which lives in the Entra-protected
# blob storage bootstrap.sh created (use_azuread_auth = true, no shared key access) —
# an accepted exposure until Entra-only auth (see local_auth_enabled above) removes
# the key from the picture entirely.
# Lab tier: regenerated by re-running Terraform when the Foundry key rotates; see the
# CKV_AZURE_41 skip below.
# tflint-ignore: azurerm_resources_missing_prevent_destroy
resource "azurerm_key_vault_secret" "foundry_api_key" {
  # checkov:skip=CKV_AZURE_41: no secret-rotation policy exists yet for the lab tier.
  # These are regenerated by re-running Terraform when the underlying Foundry key
  # rotates, not on a calendar; a fixed expiration_date would need manual bumping
  # before every expiry with nothing here to catch a missed one, which is worse than
  # no expiry.
  name         = "foundry-api-key"
  value        = azurerm_cognitive_account.foundry.primary_access_key
  key_vault_id = azurerm_key_vault.lab.id
  content_type = "text/plain"

  depends_on = [azurerm_role_assignment.kv_secrets_officer]
}

# Same reason as foundry_api_key above.
# tflint-ignore: azurerm_resources_missing_prevent_destroy
resource "azurerm_key_vault_secret" "foundry_endpoint" {
  # checkov:skip=CKV_AZURE_41: same reason as foundry_api_key above.
  name         = "foundry-endpoint"
  value        = azurerm_cognitive_account.foundry.endpoint
  key_vault_id = azurerm_key_vault.lab.id
  content_type = "text/plain"

  depends_on = [azurerm_role_assignment.kv_secrets_officer]
}
